### ISSUE TITLE
CI issue

### ISSUE THREAD

**Issue by freshlogic** [mediocre/mehdown#109]
https://github.com/mediocre/mehdown/pull/108

**Comment by javamatte** [comment]
The build failed due to a Coveralls outage. Rerunning the build resulted in a success.

<img width="1220" alt="Screen Shot 2021-09-01 at 8 10 46 AM" src="https://user-images.githubusercontent.com/2159184/131697222-8974616b-4447-4bdb-8166-c5083c9a4f26.png">

**Comment by freshlogic** [comment]
@javamatte Isn't the root cause of the issue that a build ran to begin with when this is a dependabot PR?

**Comment by javamatte** [comment]
I was about to reply that mehdown doesn't have any dependencies on private repos or Secrets, so it's dependabot should perform correctly.

Unfortunately, it has one important secret: COVERALLS_REPO_TOKEN 🤣 

We could make a separate workflow (with the action filter for dependabot-only branches) to skip coveralls if we want to have dependabot builds work on the public repo.
