### ISSUE TITLE
Link resized image to full-size (direct) image

### ISSUE THREAD

**Issue by davebug** [mediocre/mehdown#23]
Clicking an image in the forum should load the full-size image (a direct link to the jpg/png/gif/whatever file url) _if_ they're not otherwise linked in mehdown to something else. 

(Potentially we should have a link border outline for images linked in mehdown vs no border for this type of link?)

**Comment by freshlogic** [comment]
Testing GFM tables

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

**Comment by freshlogic** [comment]
Inline `code`

```
fenced code
```

**Comment by oparamo** [comment]
Hey everyone, I made a PR that addresses this issue here: https://github.com/mediocre/mehdown/pull/55. If I misunderstood the issue or there's something I could do better please let me know 👍
