### ISSUE TITLE
Url parser has trouble with urls ending in a period

### ISSUE THREAD

**Issue by mattschuette** [mediocre/mehdown#77]
"Why would a url end in a period?" I hear you ask. "That's a dumb thing no one would do." I hear you grumble. Well, let me introduce you to a little site called fucking WIkipedia. If there is a dumb thing to do in urls, they do the shit out of it.  So, I noticed this here: https://meh.com/forum/topics/why-am-i-being-charged-tax-now#5cefd6895de68e0e2014d744. I did test, in a whisper, if the square bracket and paren form would work, which of course it does. It's just a url in free text that isn't recognized. Honestly, I don't know that it should be. Ninety-nine times out of a hundred, it's a sentence that has a url at the end, and of course you don't consume the punctuation.

**Comment by freshlogic** [comment]
Closing. I don't see a way to solve this and it seems appropriate to let other Markdown syntax handle this scenario.
