### ISSUE TITLE
Proposal: Add oEmbed support

### ISSUE THREAD

**Issue by 10by10pixel** [mediocre/mehdown#94]
Currently, all automatic embeds from links are done on a site-by-site basis.  I'm not sure if this was an intentional  move or if the goal was to support as many sites as possible without allowing arbitrary iframes/scripts. Assuming it's the latter it might be a good idea to implement [oembed](https://oembed.com/) support, which will allow mehdown to support [hundreds](https://oembed.com/providers.json) more sites with what I believe would actually be a reduction in code size. oEmbed is fairly well known and supported so there are libraries one could use to do a lot of the heavy lifting.

**Comment by freshlogic** [comment]
Sounds good to me @10by10pixel. Are you interested in writing it?

**Comment by 10by10pixel** [comment]
I could give it a shot but this would be my first NODE.JS project.
